### ISSUE TITLE
Thanks for the great work.

### ISSUE THREAD

**Issue by ccmCCMfk** [yzqin/dex-hand-teleop#1]
I got the program running.Are there some methods to adjust the back and forward movement of the hand.In my experiment,the hand didn't move back and forward well,it's okay to move left and right.

**Comment by ccmCCMfk** [comment]
And when I try to control the hand,my real-world hand often moves beyond the camera frame.Do you know how to solve this problem.

**Comment by yzqin** [comment]
If you're looking to adjust the default correlation between the coordinates of the human hand and the simulation of the robot hand, you may consider altering the orientation [at this particular line of code](https://github.com/yzqin/dex-hand-teleop/blob/bab50695dd4cb04e88d6c58a16727e9b3d9efb13/example/teleop_collect_data.py#L106). Experiment with the Euler angle in this section to modify the standard forward and reverse movements.

Regarding the issue of the hand exceeding the space limit, a possible workaround could be to initiate the teleoperation with your hand positioned further from the camera. This offers the camera an enhanced field of perception.

**Comment by ccmCCMfk** [comment]
> If you're looking to adjust the default correlation between the coordinates of the human hand and the simulation of the robot hand, you may consider altering the orientation [at this particular line of code](https://github.com/yzqin/dex-hand-teleop/blob/bab50695dd4cb04e88d6c58a16727e9b3d9efb13/example/teleop_collect_data.py#L106). Experiment with the Euler angle in this section to modify the standard forward and reverse movements.
> 
> Regarding the issue of the hand exceeding the space limit, a possible workaround could be to initiate the teleoperation with your hand positioned further from the camera. This offers the camera an enhanced field of perception.

thanks!
