### ISSUE TITLE
How to use properly the code

### ISSUE THREAD

**Issue by AdrianPrados** [yzqin/dex-hand-teleop#10]
Good afternoon, I am using the code provided for my own robotic hand. I have been able to load it correctly but the steps to follow are not very clear. What I have followed so far is:

1) Launch **teleop_collect_data.py** for one of the proposed tasks (for example the task of opening the door).
2) Repeat the process modifying the name of the data (default is **0000.pkl**, I take different data until I get about 30 demos).

Once I have this, I don't know how to continue to use the DAPG. I don't know exactly if I have to launch some additional process to generate the .pkl of the imitation process to be later reproduced with the code **replay_generate_bc_data.py**. Could you tell me which are the steps to follow? Maybe i am doing something wrong and instead of recording different pkl for each demostrantion, has to be all of them in the same demonstration (instead of 0000.pkl,0001.pkl,0002.pkl... it has to be just one 0000.pkl that contain all the demosntrations)
 Thank you very much for your work.

**Comment by yzqin** [comment]
Pipeline:

1. Collect data file 0000.pkl -> 00xx.pkl (e.g. 0050.pkl) on the cutomized robot hand
2. Generate training data by retargeting using replay_generate_bc_data.py.  for other robot hand.
3. Train DAPG using the generated data.
