### ISSUE TITLE
Mimic joint constraints

### ISSUE THREAD

**Issue by enyen** [yzqin/dex-hand-teleop#11]
Both Adroit and SVH hand have mimic joint constraints due to mechanical couplings.
If not handled implicitly by Sapien https://github.com/haosulab/SAPIEN/issues/68, are they being handled in the retargeting optimozation process?

**Comment by yzqin** [comment]
Great question. For the retargeting code in this repo back to 2022, I do not handle mimic joint explicitly. However, my new [retargeting repo](https://github.com/dexsuite/dex-retargeting) does deal with the mimic joint, maybe you can try that and use the new retargeting lib to do teleoperation and data processing. The code to handle mimic joint is [here](https://github.com/dexsuite/dex-retargeting/blob/ee18b9292fb4279cc223aeec15b5f7802dd3d182/dex_retargeting/kinematics_adaptor.py#L44)

By the way, from the [pre-release SAPIEN(3.0.0x)](https://pypi.org/project/sapien/#history), the mimic joint constraints are handled implicitly by SAPIEN.
