### ISSUE TITLE
Real-World Alignment and Transferability of Robot Model in Simulation for Allegro Hand Configuration

### ISSUE THREAD

**Issue by JackMa-coder** [yzqin/dex-hand-teleop#14]
Thanks for your great work!
I am curious to know whether you have developed a robot model in the simulation environment (Section VII D: Real-World Robot Experiments) that aligns with real-world conditions. Is it feasible to apply the model trained under the previous flying hand configuration directly to the robot model within this simulation? If so, the robot perception defined in the Task Setup of Section VII D should correspond to the joint angles and palm velocities outlined in Section VII B: State and Action. Specifically, the joint angle in question is only related to the Allegro multi-fingered hand, not XArm6. Could you please confirm if my understanding is accurate?

**Comment by yzqin** [comment]
That is a great question.

Yes, we developed a robot model in the sim with both arms and hands.
To train this arm-hand model, we actually perform retargeting from a flying hand to a whole arm-hand robot and generate the demonstrations for the full robot. In this case, the joint angles include both allegro and xarm in order to perform sim2real experiments.

**Comment by JackMa-coder** [comment]
> That is a great question.
> 
> Yes, we developed a robot model in the sim with both arms and hands. To train this arm-hand model, we actually perform retargeting from a flying hand to a whole arm-hand robot and generate the demonstrations for the full robot. In this case, the joint angles include both allegro and xarm in order to perform sim2real experiments.

The inclusion of both allegro and xarm joint angles for sim2real experiments is a crucial aspect that I find particularly interesting. Your insights are incredibly helpful, and I appreciate the time you took to explain this. Many thanks again! 
﻿
