### ISSUE TITLE
Robot Assets

### ISSUE THREAD

**Issue by zzilch** [yzqin/dex-hand-teleop#2]
Where can I get the assets for robot to run `example/replay_generate_bc_data.py'

**Comment by zzilch** [comment]
Found in DexPoint. Right?

**Comment by yzqin** [comment]
Sorry for the confusion. The missing robot assets are updated in 70f453a252c5c3db340c46fbf856c683de45abd9. You can also the assets in DexPoint, they are the same.

**Comment by yzqin** [comment]
Close this issue since the missing assets are fixed via 70f453a252c5c3db340c46fbf856c683de45abd9
