### ISSUE TITLE
Choice of optimization algorithm

### ISSUE THREAD

**Issue by fedeceola** [yzqin/dex-hand-teleop#3]
Hi, I am using your code to retarget a 5-fingered hand different from the ones considered for your experiments. I am running the code in [optimizer.py](https://github.com/yzqin/dex-hand-teleop/blob/70f453a252c5c3db340c46fbf856c683de45abd9/hand_teleop/kinematics/optimizer.py) and I noticed that it is quite common to have `nlopt failure` errors. For example, this happens changing the following line:
https://github.com/yzqin/dex-hand-teleop/blob/70f453a252c5c3db340c46fbf856c683de45abd9/hand_teleop/kinematics/optimizer.py#L161
into:
```init_qpos = np.clip(random_qpos + 0.1, joint_limit[:, 0], joint_limit[:, 1])```
I tried to modify the algorithm used for optimization in `nlpopt` and the amount of `nlopt failure` errors decreases. Are there any motivations to choose the `LD_LBFGS` algorithm for optimization? Did you experience any problems with different algorithms? Thanks in advance!

**Comment by yzqin** [comment]
Hi @fedeceola 

Thanks for reaching out. In my experiments, I've experimented with various optimizers and observed that the choice of optimizer doesn't significantly impact the results. I found the `LD_LBFGS` optimizer to be slightly superior, even though there's no theoretical justification for its performance. It's possible that other optimizers might yield better results in differing contexts.

As for modifying the termination condition of the optimization, be aware that this could result in an `nlopt failure` if the condition is overly strict and unattainable. Interestingly, I've noticed that reasonable results can still be achieved at times even when `nlopt failure` is indicated.

Lastly, could you share the new hand urdf you're currently working with? I'd be interested in inspecting it.

**Comment by fedeceola** [comment]
Hi @yzqin, thanks for your reply. I'll play a bit with different algorithms then.

> Interestingly, I've noticed that reasonable results can still be achieved at times even when `nlopt failure` is indicated.

But, according to this line of code

https://github.com/yzqin/dex-hand-teleop/blob/70f453a252c5c3db340c46fbf856c683de45abd9/hand_teleop/kinematics/optimizer.py#L126

this happens only if the expected `qpos` of the target is close to the initial `qpos`, right?

> Lastly, could you share the new hand urdf you're currently working with? I'd be interested in inspecting it.

I'm using a the Seed Hand RH8DR model. Unfortunately, I cannot share the model as requested by Seed Robotics.

**Comment by yzqin** [comment]
`this happens only if the expected qpos of the target is close to the initial qpos, right?` Yes. It only happens when you are re-targeting a hand pose trajectory to a new robot and the difference between consequent pose is small.
