### ISSUE TITLE
assets/misc

### ISSUE THREAD

**Issue by ccmCCMfk** [yzqin/dex-hand-teleop#4]
It seems that assets/misc/ktx/day.ktx were missing.when I run replay_generate_bc_data.py:
RuntimeError: filesystem error: cannot make canonical path: No such file or directory [/home/ustc/PycharmProjects/dex-hand-teleop/assets/misc/ktx/day.ktx]

**Comment by yzqin** [comment]
As mentioned in the [installation guide](https://github.com/yzqin/dex-hand-teleop#installation), you need to download the `day.ktx` from the provided from [Google Drive Link](https://drive.google.com/file/d/1Xe3jgcIUZm_8yaFUsHnO7WJWr8cV41fE/view?usp=sharing). Place the `day.ktx` at `assets/misc/ktx/day.ktx`.

**Comment by ccmCCMfk** [comment]
Thank you,it works.
