### ISSUE TITLE
hand pose estimation

### ISSUE THREAD

**Issue by JiaheXu** [yzqin/dex-hand-teleop#5]
Hi @yzqin 

Great work!!! I would like to know which hand pose estimation method is better, the method used in this paper or the one used in dexmv-sim? What's the difference between them and why did you choose a new method for hand pose estimation?

**Comment by yzqin** [comment]
Hi @JiaheXu ,

That's an excellent question. The DexMV hand pose estimation algorithm employs an optimization-based post-processing method. While this approach can enhance performance and temporal coherence, it does so at the expense of processing time. Consequently, it isn't feasible for real-time applications, making it unsuitable for teleoperation. The algorithm used in this repository, on the other hand, is more lightweight and is capable of real-time hand tracking.
