### ISSUE TITLE
No module named 'hand_detector'

### ISSUE THREAD

**Issue by zhengbi-yong** [yzqin/dex-hand-teleop#7]
`(dexteleop) (base) *****@*****:~/dex-hand-teleop$ /home/*****/anaconda3/envs/dexteleop/bin/python /home/*****/dex-hand-teleop/example/teleop_collect_data.py
Traceback (most recent call last):
  File "/home/*****/dex-hand-teleop/example/teleop_collect_data.py", line 7, in <module>
    from hand_detector.hand_monitor import Record3DSingleHandMotionControl
ModuleNotFoundError: No module named 'hand_detector'`

When I try to run the teleop_collect_data.py file, I encounter the aforementioned error. Could you advise on how to resolve this issue? Did I make a mistake during the installation process?

**Comment by yzqin** [comment]
Hi @zhengbi-yong ,

The `hand_detector` directory is [here in the repo](https://github.com/yzqin/dex-hand-teleop/tree/main/hand_teleop). Maybe you can simply add the environment variable before running the python code.

```shell
cd dex-hand-teleop
export PYTHONPATH=`pwd`
python3 example/teleop_collect_data.py
```

**Comment by zhengbi-yong** [comment]
`PYTHONPATH="." /home/****/anaconda3/envs/dexteleop/bin/python /home/****/dex-hand-teleop/example/teleop_collect_data.py`
Adding the project's root directory to sys.path should resolve the issue. Thank you.
