### ISSUE TITLE
Releasing training data

### ISSUE THREAD

**Issue by enyen** [yzqin/dex-hand-teleop#9]
Do you have any plan to release the 50 collected demo used for training in each task?
Thanks!

**Comment by yzqin** [comment]
hi @enyen 

I apologize that I can not find the original demonstrations collected. Now the data collection tool is here in this repo, I believe that you do not need much effort to collect just 50 demonstrations for each task, and also create your new environment for data collection.

**Comment by enyen** [comment]
No problem!
